spring:
  datasource:
    # Maria DB
    url: jdbc:mariadb://znzn.synology.me:3306/jwt_sample
    username: jwt_sample
    password: jwtsample!

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

logging:
  level:
    com.znzn: debug